### ISSUE TITLE
add simd128 software implementation 

### ISSUE THREAD

**Issue by calvin2021y** [aegis-aead/libaegis#12]
now all browser support simd128,   it will be great to have a simd128 optimization implementation

**Comment by jedisct1** [comment]
Are you using this within an emacripten project?

**Comment by calvin2021y** [comment]
Yes.  

I think wasi-sdk also cloud benefit from simd128 support.

**Comment by jedisct1** [comment]
LLVM's auto-vectorisation is enough to enable usage of `simd128` everywhere it matters.

For example `softaes_block_load` becomes:

```asm
        local.get       0
        local.get       1
        v128.load       0:p2align=0
        v128.store      0:p2align=2
```

And `block_xor` becomes:

```asm
        local.get       0
        local.get       2
        v128.load       0:p2align=2
        local.get       1
        v128.load       0:p2align=2
        v128.xor
        v128.store      0:p2align=2
```

So a custom implementation would be redundant.

All browsers also support bulk memory operations, so in order to enable all this, just compile with `-Dcpu=baseline+bulk_memory+simd128`:

```sh
zig build -Dtarget=wasm32-freestanding -Drelease -Dfavor-performance \
          -Dcpu=baseline+bulk_memory+simd128
```

For web browsers, you may want to compile to `wasm32-freestanding`, as browsers don't implement `wasi`, and `libaegis` doesn't require `wasi` either, except for benchmarks.

`simd128` indeed gives a little performance improvement (at least using `wasmer`, but it should be comparable with browser engines):

* Baseline (`zig build -Dtarget=wasm32-wasi -Dcpu=baseline -Dwith-benchmark -Drelease -Dfavor-performance`):

```text
AEGIS-256	   1780.83 Mb/s
AEGIS-256X2	   1525.60 Mb/s
AEGIS-256X4	   1405.54 Mb/s
AEGIS-128L	   2577.91 Mb/s
AEGIS-128X2	   2206.03 Mb/s
AEGIS-128X4	   1939.27 Mb/s
AEGIS-128L MAC	   2722.78 Mb/s
AEGIS-128X2 MAC	   2507.06 Mb/s
AEGIS-128X4 MAC	   2226.92 Mb/s
AEGIS-256 MAC	   1858.31 Mb/s
AEGIS-256X2 MAC	   1734.12 Mb/s
AEGIS-256X4 MAC	   1571.91 Mb/s
```

* bulk-memory+simd128 (`zig build -Dtarget=wasm32-wasi -Dcpu=baseline+bulk_memory+simd128 -Dwith-benchmark -Drelease`)

```text
AEGIS-256	   1847.78 Mb/s
AEGIS-256X2	   1701.35 Mb/s
AEGIS-256X4	   1543.56 Mb/s
AEGIS-128L	   2746.18 Mb/s
AEGIS-128X2	   2492.91 Mb/s
AEGIS-128X4	   2203.02 Mb/s
AEGIS-128L MAC	   2652.77 Mb/s
AEGIS-128X2 MAC	   2630.31 Mb/s
AEGIS-128X4 MAC	   2375.44 Mb/s
AEGIS-256 MAC	   1848.31 Mb/s
AEGIS-256X2 MAC	   1783.15 Mb/s
AEGIS-256X4 MAC	   1644.50 Mb/s
```

With `emscripten`, adding `-msimd128` should do the same thing.
