### ISSUE TITLE
Is order of members in MAC state structure correct for AEGIS128L?

### ISSUE THREAD

**Issue by utelle** [aegis-aead/libaegis#14]
For AEGIS128L I see the following MAC state structure:
https://github.com/aegis-aead/libaegis/blob/78b069336a0e4770042f8d1e91727ad0d0c16c54/src/aegis128l/aegis128l_common.h#L306-L312

However, for all other variants  the order of the members `blocks0` and `blocks`is 
```C
     aegis_blocks blocks; 
     aegis_blocks blocks0; 
```
Shouldn't it be in this order for AEGIS128L, too?

**Comment by jedisct1** [comment]
Good catch.

Since this is an opaque structure, it has not implications on applications. `blocks` is used more frequently than `blocks0`, so on some architectures, placing it first may avoid an extra pointer addition.

I'm going to change this, thanks!

**Comment by jedisct1** [comment]
Closed by 18439cd58f50b23825620138abe6f1cbe705b69d

Thanks!

**Comment by jedisct1** [comment]
Now that the constructions are finalized, just to let you know what changes I'd like to make to libaegis before 1.0.0 is tagged:
- Get rid of `TAILBYTES`. This is only for the encryption streaming API. In the [openssl patch](https://github.com/aegis-aead/openssl), `encrypt/decrypt` return the same amount of bytes as the input, which makes usage easier. The same can be done in `libaegis`.
- *Maybe* replace the protected software implementations with bitsliced implementations as in [aegis-bitsliced](https://github.com/aegis-aead/aegis-bitsliced). Not sure about that, since it requires quite different implementations.
- *Maybe* bring the assembly implementations from [aegis-jasmin](https://github.com/aegis-aead/aegis-jasmin), since they perform well according to e.g. [1](https://bench.cr.yp.to/impl-aead/aegis128x2.html), and will perform the same regardless of the compiler Not sure about that either, since sharing almost the same C code for all architectures is easier to understand and maintain.
- But that's pretty much it, really.

A RISC-V implementation would be great, but I don't have access to any RISC-V CPU having the crypto extensions. That will have to wait.

**Comment by jedisct1** [comment]
The trick from 2ee63911bf710e4ce8863f359b3c29882600e662 also needs to be explored. But that requires a lot of testing on different platforms, and will complicate implementations. So, that will probably happen after 1.0.0.

**Comment by utelle** [comment]
> Now that the constructions are finalized,

Regarding the MAC related functions I have one question. You multiplied the argument `maclen` with 8 (`maclen << 3`) in the `AES_BLOCK_LOAD_64x2` function calls in one of your last commits. However, you did not do that for the arguments `d` in the same function calls. Is that on purpose?

Another question I have is the implementation of the functions `aegis???_pick_best_implementation`, for example for `aegis128l`:

https://github.com/aegis-aead/libaegis/blob/18439cd58f50b23825620138abe6f1cbe705b69d/src/aegis128l/aegis128l.c#L231-L259

If during compile the symbol `HAS_HW_AES` was defined, but if then the executable runs on a machine not having AES hardware support for whatever reason, the function would not set the variable `implementation` at all, but would still return `0`. IMHO this is somewhat unexpected. In my fork the _soft AES_ configuration is always compiled into the executable, so that the library will always work, no matter whether AES hardware support is available or not.

> just to let you know what changes I'd like to make to libaegis before 1.0.0 is tagged:
> 
> * Get rid of `TAILBYTES`. This is only for the encryption streaming API. In the [openssl patch](https://github.com/aegis-aead/openssl), `encrypt/decrypt` return the same amount of bytes as the input, which makes usage easier. The same can be done in `libaegis`.

Returning output with the same lenghth as the input is certainly preferrable.

> * _Maybe_ replace the protected software implementations with bitsliced implementations as in [aegis-bitsliced](https://github.com/aegis-aead/aegis-bitsliced). Not sure about that, since it requires quite different implementations.

I'm not sure about the implications. What would be the benefit?

> * _Maybe_ bring the assembly implementations from [aegis-jasmin](https://github.com/aegis-aead/aegis-jasmin), since they perform well according to e.g. [1](https://bench.cr.yp.to/impl-aead/aegis128x2.html), and will perform the same regardless of the compiler Not sure about that either, since sharing almost the same C code for all architectures is easier to understand and maintain.

Personally, I'm quite happy with the C implementation. Struggling with various assembly implementations can be a hassle.

> A RISC-V implementation would be great, but I don't have access to any RISC-V CPU having the crypto extensions. That will have to wait.

Maybe this problem could be solved with [QEMU](https://www.qemu.org). According to the [QEMU documanetation](https://www.qemu.org/docs/master/system/target-riscv.html) QEMU can emulate both 32-bit and 64-bit RISC-V CPUs.

For _SQLite3 Multiple Ciphers_ I use QEMU in a GitHub workflow to test it for the `aarch64` platform.

**Comment by jedisct1** [comment]
> Regarding the MAC related functions I have one question. You multiplied the argument `maclen` with 8 (`maclen << 3`) in the `AES_BLOCK_LOAD_64x2` function calls in one of your last commits. However, you did not do that for the arguments `d` in the same function calls. Is that on purpose?

Yes. Lengths are in bits. This simplifies the specification and avoids mixing bits and bytes.
But `d` is the parallelism degree, not a length.

See https://www.ietf.org/archive/id/draft-irtf-cfrg-aegis-aead-14.html#name-aegis-as-a-message-authenti

**Comment by jedisct1** [comment]
> If during compile the symbol `HAS_HW_AES` was defined, but if then the executable runs on a machine not having AES hardware support for whatever reason, the function would not set the variable `implementation` at all, but would still return `0`.

`HAS_HW_AES` is defined when the target is guaranteed to have AES, so that software implementations and CPU detection are not necessary. The resulting binary of not portable except with targets such as Apple Silicon or Windows ARM64, that all have AES.

**Comment by jedisct1** [comment]
> > * _Maybe_ replace the protected software implementations with bitsliced implementations as in [aegis-bitsliced](https://github.com/aegis-aead/aegis-bitsliced). Not sure about that, since it requires quite different implementations.
> 
> I'm not sure about the implications. What would be the benefit?

Without hardware support, anything based on AES has two options:
- be reasonably fast but possibly leak data via side channels due to lookups across different cache lines (or even the same cache line, with hyperthreading)
- be protected against side channels, but slow.

In practice, whether side channels are an issue or not really depend on the applications, platform and threat model. If an adversary has physical access to the hardware, that can be devastating. If not, with the increase of architectural attacks and shared cloud environments, it's still a risk even though most published attacks are hard to reproduce outside a very controlled environment.

In software mode, `libaegis` has protection, but this is very slow. However `FAVOR_PERFORMANCE` can be defined to be fast but not care about side channels.

Bitslicing is a different representation of the AES state, that protects against side channels and is faster and more reliable than the other protection technique. It's only applicable to some ciphers, but was found to be applicable to AEGIS, at least to the 128* variants.

In practice, setting `FAVOR_PERFORMANCE` is probably fine everywhere, except on embedded systems where people can have physical access to the device, and where the CPU runs slowly enough that reliable measurements can be performed. In that context, bitslicing is the best option.

**Comment by jedisct1** [comment]
> Personally, I'm quite happy with the C implementation. Struggling with various assembly implementations can be a hassle.

I agree. People who really want the best performance can always use the Zig or Assembly implementations directly.
For `libaegis`, maintainability and consistency is more important.
 
> > A RISC-V implementation would be great, but I don't have access to any RISC-V CPU having the crypto extensions. That will have to wait.
> 
> Maybe this problem could be solved with [QEMU](https://www.qemu.org). According to the [QEMU documanetation](https://www.qemu.org/docs/master/system/target-riscv.html) QEMU can emulate both 32-bit and 64-bit RISC-V CPUs.

I don't think it supports the crypto extensions yet.

**Comment by utelle** [comment]
> > > A RISC-V implementation would be great, but I don't have access to any RISC-V CPU having the crypto extensions. That will have to wait.
> > 
> > 
> > Maybe this problem could be solved with [QEMU](https://www.qemu.org). According to the [QEMU documanetation](https://www.qemu.org/docs/master/system/target-riscv.html) QEMU can emulate both 32-bit and 64-bit RISC-V CPUs.
> 
> I don't think it supports the crypto extensions yet.

I found this article [Adding RISC-V Vector Cryptography Extension support to QEMU](https://www.codethink.co.uk/articles/2023/vcrypto_qemu/) and [this reddit discussion](https://www.reddit.com/r/RISCV/comments/184cusi/running_qemu_with_support_for_riscv_vector/). So, it might be possible to use QEMU.

**Comment by utelle** [comment]
> `HAS_HW_AES` is defined when the target is guaranteed to have AES, so that software implementations and CPU detection are not necessary.

Hm, but why does the code check CPU features then, if it is not necessary?

Unfortunately, I don't have older hardware without AES support at hand, so that I can't check whether a binary created by Visual C++ does not run on it if I explicitly request certain hardware features in the code generation section of the compiler settings.

**Comment by utelle** [comment]
> Without hardware support, anything based on AES has two options:
> 
> * be reasonably fast but possibly leak data via side channels due to lookups across different cache lines (or even the same cache line, with hyperthreading)
> * be protected against side channels, but slow.
> 
> In practice, whether side channels are an issue or not really depend on the applications, platform and threat model. If an adversary has physical access to the hardware, that can be devastating. If not, with the increase of architectural attacks and shared cloud environments, it's still a risk even though most published attacks are hard to reproduce outside a very controlled environment.

Regarding my use case - encrypting SQLite databases at rest - the simplest approach of an adversary with physical access to the hardware would be to intercept the input of the passphrase. That would allow unlimited access to the database.

The goal is to secure the database file while it resides on disk or is transferred from one location to another. Securing a running application which uses SQLite would require different measures.

> In software mode, `libaegis` has protection, but this is very slow. However `FAVOR_PERFORMANCE` can be defined to be fast but not care about side channels.
> 
> Bitslicing is a different representation of the AES state, that protects against side channels and is faster and more reliable than the other protection technique. It's only applicable to some ciphers, but was found to be applicable to AEGIS, at least to the 128* variants.

Thanks for the clarifications.

**Comment by jedisct1** [comment]
> Hm, but why does the code check CPU features then, if it is not necessary?

Because AES is one thing, but AVX2, AVX512, are something else.

If HAS_HW_AES is set, it only means that software AES implementations don't need to be included.

**Comment by utelle** [comment]
> Because AES is one thing, but AVX2, AVX512, are something else.

For the `x86/x64` based AEGIS variants where there exist more than one implementation like `AVX`, `AVX2`, and `AVX512` I understand that. But for `ARM Crypto` and `AltiVec` all AEGIS variants have exactly one implementation. In those cases checking the CPU features shouldn't be necessary. Or am I missing something?

**Comment by jedisct1** [comment]
Newer ARM chips have SVE extensions for which implementations will be added once I manage to get access to such a chip.
